//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb2.LagerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vara", Namespace="http://schemas.datacontract.org/2004/07/LagerService")]
    [System.SerializableAttribute()]
    public partial class Vara : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ButikAntalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LagerAntalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PrisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ButikAntal {
            get {
                return this.ButikAntalField;
            }
            set {
                if ((this.ButikAntalField.Equals(value) != true)) {
                    this.ButikAntalField = value;
                    this.RaisePropertyChanged("ButikAntal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LagerAntal {
            get {
                return this.LagerAntalField;
            }
            set {
                if ((this.LagerAntalField.Equals(value) != true)) {
                    this.LagerAntalField = value;
                    this.RaisePropertyChanged("LagerAntal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Namn {
            get {
                return this.NamnField;
            }
            set {
                if ((object.ReferenceEquals(this.NamnField, value) != true)) {
                    this.NamnField = value;
                    this.RaisePropertyChanged("Namn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Pris {
            get {
                return this.PrisField;
            }
            set {
                if ((this.PrisField.Equals(value) != true)) {
                    this.PrisField = value;
                    this.RaisePropertyChanged("Pris");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LagerServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListVara", ReplyAction="http://tempuri.org/IService1/GetListVaraResponse")]
        Labb2.LagerServiceReference.Vara[] GetListVara();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListVara", ReplyAction="http://tempuri.org/IService1/GetListVaraResponse")]
        System.Threading.Tasks.Task<Labb2.LagerServiceReference.Vara[]> GetListVaraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OrderVaraFromStorage", ReplyAction="http://tempuri.org/IService1/OrderVaraFromStorageResponse")]
        void OrderVaraFromStorage(int ID, int Antal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OrderVaraFromStorage", ReplyAction="http://tempuri.org/IService1/OrderVaraFromStorageResponse")]
        System.Threading.Tasks.Task OrderVaraFromStorageAsync(int ID, int Antal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Labb2.LagerServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Labb2.LagerServiceReference.IService1>, Labb2.LagerServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Labb2.LagerServiceReference.Vara[] GetListVara() {
            return base.Channel.GetListVara();
        }
        
        public System.Threading.Tasks.Task<Labb2.LagerServiceReference.Vara[]> GetListVaraAsync() {
            return base.Channel.GetListVaraAsync();
        }
        
        public void OrderVaraFromStorage(int ID, int Antal) {
            base.Channel.OrderVaraFromStorage(ID, Antal);
        }
        
        public System.Threading.Tasks.Task OrderVaraFromStorageAsync(int ID, int Antal) {
            return base.Channel.OrderVaraFromStorageAsync(ID, Antal);
        }
    }
}
